<?php
$frameworks = array("Abbottabad",
"Adezai",
"Ali Bandar",
"Amir Chah",
"Attock",
"Ayubia",
"Bahawalpur",
"Bahawalnagar",
"Burewala",
"Bhakkar",
"Chiniot",
"Chakwal",
"Chitral",
"Dadu",
"Dera Ghazi Khan",
"Dera Ismail Khan",
"Daska",
"Dera Bugti",
"Digri",
"Faisalabad",
"Ghotki",
"Gwadar",
"Gujranwala",
"Gujrat",
"Hyderabad",
"Haripur",
"Hafizabad",
"Hasilpur",
"Haveli Lakha",
"Islamabad",
"Jacobabad",
"Jamshoro",
"Jhang",
"Jhelum",
"Karachi",
"Kamokey",
"Kashmor",
"Kasur",
"Khairpur",
"Khanpur",
"Khanewal",
"Kohat",
"Korangi",
"Lahore",
"Lasbela",
"Layyah",
"Liari",
"Lodhran",
"Multan",
"Mandi Bahauddin",
"Mirpur",
"Mianwali",
"Mirpur Khas",
"Muzaffar Garh",
"Muzaffarabad",
"Nawabshah",
"Nazimabad",
"Nowshera",
"Okara",
"Peshawar",
"Quetta",
"Rawalpindi",
"Rahim Yar Khan",
"Rajan Pur",
"Ranipur",
"Rawalakot",
"Rohri",
"Sialkot",
"Sadiqabad",
"Sahiwal",
"Sargodha",
"Sheikhupura",
"Shikarpur",
"Sui",
"Sukkur",
"Swabi",
"Swat",
"Tando Adam",
"Thatta",
"Toba Tek Singh",
"Umarao",
"Umarkot",
"Vehari",
"Wadh",
"Wah Cantt",
"Wazirabad",
"Yakmach",
"Zhob") ;
$name = $_GET["name"];
if (strlen($name) > 0) {
    $match = "";
    for ($i = 0; $i < count($frameworks); $i++) {
        if (strtolower($name) == strtolower(substr($frameworks[$i], 0, strlen($name)))) {
            if ($match == "") {
                $match = $frameworks[$i];
            } else {
                $match = $match . " , " . $frameworks[$i];
            }
        }
    }
}
echo ($match == "") ? 'no match found' : $match;
?>